### ISSUE TITLE
fix pyallpay for python3 / pypy3 

### ISSUE THREAD

**Issue by m85091081** [lockys/allPay.py#2]
## i fix it 

現在他可以在 python3 用了

**Comment by lockys** [comment]
請問你要 pull request 嗎?
或著你要 standalone?

**Comment by m85091081** [comment]
Standalone 好了 畢竟有些語法在 Python2`和3不共通

**Comment by lockys** [comment]
ok, 我把你加到 readme.

**Comment by lockys** [comment]
@m85091081 
Would you like to become the collaborator or owner of this repo?
Currently, I would not maintain the module due to personal reasons.
If you would like to become the owner, I would transfer the ownership of this repo to you.
Or if you just want to become the collaborator, I could add you as collaborator.
I think there is a way to integrate the code of Python3 and Python2. For example,
For python3, use

``` python
import py3allpay
```

but for Python2, use

```
import py2allpay
```

But, it's all in the same module `pyallpay`. 
People only need to `pip install pyallpay` instead of `pip install py3allpay`.
Or, Do you have better recommendations to do this?
